spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/bidding_user_db
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=SECRET-KEY
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000